from app.exceptions.library import (
    BookNotFound,
    BookNotAvailable,
    BorrowingNotFound,
    BorrowLimitExceeded,
    DuplicateActiveBorrowing,
    BookAlreadyReturned,
    AgeRestricted,
    AgeVerificationRequired,
    AccountSuspended,
    ExtensionLimitReached,
    CannotExtendOverdue,
)
from app.exceptions.auth import (
    InvalidCredentials,
    InvalidToken,
    InsufficientPermissions,
    UserNotFound,
    UsernameAlreadyExists,
    EmailAlreadyExists,
    InvalidResetToken,
    CannotSelfModify,
    LastAdminProtected,
)

__all__ = [
    "BookNotFound",
    "BookNotAvailable",
    "BorrowingNotFound",
    "BorrowLimitExceeded",
    "DuplicateActiveBorrowing",
    "BookAlreadyReturned",
    "AgeRestricted",
    "AgeVerificationRequired",
    "AccountSuspended",
    "ExtensionLimitReached",
    "CannotExtendOverdue",
    "InvalidCredentials",
    "InvalidToken",
    "InsufficientPermissions",
    "UserNotFound",
    "UsernameAlreadyExists",
    "EmailAlreadyExists",
    "InvalidResetToken",
    "CannotSelfModify",
    "LastAdminProtected",
]
